# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SPPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SPPlayer
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'Kingfisher'

end

target 'SPPlayerShare' do
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.0'
end